# Linear algebra

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.3'

## Matrix and vector products

Q1. Predict the results of the following code.

In [5]:
x = [1,2]
y = [[4, 1], [2, 2]]
print(np.dot(x, y))
print(np.dot(y, x))
print(np.matmul(x, y))
print(np.inner(x, y))
print(np.inner(y, x))

[8 5]
[6 6]
[8 5]
[6 6]
[6 6]


Q2. Predict the results of the following code.

In [9]:
x = [[1, 0], [0, 1]]
y = [[4, 1], [2, 2], [1, 1]]
print(np.dot(y, x), "\n")
print(np.matmul(y, x))

[[4 1]
 [2 2]
 [1 1]] 

[[4 1]
 [2 2]
 [1 1]]


Q3. Predict the results of the following code.

In [17]:
x = np.array([[1, 4], [5, 6]])
y = np.array([[4, 1], [2, 2]])
print(np.vdot(x, y))
print(np.vdot(y, x))
print(np.dot(x.flatten(), y.flatten()))
print(np.inner(x.flatten(), y.flatten()))
print((x*y).sum())

30
30
30
30
30


Q4. Predict the results of the following code.

In [21]:
x = np.array(['a', 'b'], dtype=object)
y = np.array([1, 2])
print(np.inner(x, y))
print(np.inner(y, x))
print(np.outer(x, y))
print(np.outer(y, x))

abb
abb
[['a' 'aa']
 ['b' 'bb']]
[['a' 'b']
 ['aa' 'bb']]


## Decompositions

Q5. Get the lower-trianglular `L` in the Cholesky decomposition of x and verify it.

In [26]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)
L = np.linalg.cholesky(x)
print(L)

[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


In [28]:
np.array_equal(np.dot(L, L.T.conjugate()), x)

True

Q6. Compute the qr factorization of x and verify it.

In [36]:
x = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=np.float32)
q, r = np.linalg.qr(x)
print("q = \n", q , "\nr =\n", r)

q = 
 [[-0.85714287  0.3942857   0.33142856]
 [-0.42857143 -0.9028571  -0.03428571]
 [ 0.2857143  -0.17142858  0.94285715]] 
r =
 [[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


In [37]:
np.allclose(np.dot(q, r), x)

True

Q7. Factor x by Singular Value Decomposition and verify it.

In [5]:
x = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)
U, s, V = np.linalg.svd(x, full_matrices=False)
print("U = \n", U , "\ns =\n", s, "\nV =\n", V)

U = 
 [[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]] 
s =
 [3.       2.236068 2.       0.      ] 
V =
 [[-0.         0.         1.        -0.         0.       ]
 [ 0.4472136  0.         0.         0.         0.8944272]
 [-0.         1.         0.        -0.         0.       ]
 [ 0.         0.         0.         1.         0.       ]]


In [6]:
np.allclose(np.dot(U, np.dot(np.diag(s), V)), x)

True

## Matrix eigenvalues

Q8. Compute the eigenvalues and right eigenvectors of x. (Name them eigenvals and eigenvecs, respectively)

In [29]:
x = np.diag((1, 2, 3))
eigenvals, eigenvecs = np.linalg.eig(x)
print("Eigen values are\n", eigenvals, "\nEigen vectors are\n", eigenvecs)

Eigen values are
 [1. 2. 3.] 
Eigen vectors are
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
x = np.diag((1, 2, 3))
eigenvals = np.linalg.eigvals(x)
eigenvecs = np.linalg.eig(x)[1]
print("Eigen values are\n", eigenvals, "\nEigen vectors are\n", eigenvecs)

Eigen values are
 [1. 2. 3.] 
Eigen vectors are
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q9. Predict the results of the following code.

In [32]:
print(np.array_equal(np.dot(x, eigenvecs), eigenvals * eigenvecs))

True


## Norms and other numbers

Q10. Calculate the Frobenius norm and the condition number of x.

In [51]:
x = np.arange(1, 10).reshape((3, 3))
a = np.linalg.norm(x, ord = 'fro')
b = np.linalg.cond(x)
print(a)
print(b)

16.881943016134134
3.813147060626918e+16


Q11. Calculate the determinant of x.

In [60]:
x = np.arange(1, 5).reshape((2, 2))
d = np.linalg.det(x)
print("%1.1f"%d)

-2.0


In [69]:
x = np.arange(1, 5).reshape((2, 2))
sign, logdet = np.linalg.slogdet(x)
print("%1.1f"%(sign * np.exp(logdet)))

-2.0


Q12. Calculate the rank of x.

In [72]:
x = np.eye(4)
rank = np.linalg.matrix_rank(x)
print(rank)

4


In [79]:
x = np.eye(4)
rank = np.linalg.svd(x)[1].size
print(rank)

4


Q13. Compute the sign and natural logarithm of the determinant of x.

In [82]:
x = np.arange(1, 5).reshape((2, 2))
sign, log = np.linalg.slogdet(x)
print(sign, log)

-1.0 0.6931471805599455


Q14. Return the sum along the diagonal of x.

In [84]:
x = np.eye(4)
dia_sum = np.diagonal(x).sum()
print(dia_sum)

4.0


In [85]:
x = np.eye(4)
dia_sum = np.trace(x)
print(dia_sum)

4.0


## Solving equations and inverting matrices

Q15. Compute the inverse of x.

In [88]:
x = np.array([[1., 2.], [3., 4.]])
a = np.linalg.inv(x)
print(a)

[[-2.   1. ]
 [ 1.5 -0.5]]
