# Array manipulation routines

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.3'

Q1. Let x be a ndarray [10, 10, 3] with all elements set to one. Reshape x so that the size of the second dimension equals 150.

In [13]:
x = np.ones([10, 10, 3])
a = np.reshape(x, [-1, 150])
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]]


Q2. Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [32]:
x = np.arange(1,7).reshape(2,3)
a = np.ravel(x)
print(a)

[1 2 3 4 5 6]


In [39]:
x = np.arange(1,7).reshape(2,3)
a = x.flatten(order='C')
print(a)

[1 2 3 4 5 6]


In [40]:
x = np.arange(1,7).reshape(2,3)
a = x.flatten(order='F')
print(a)

[1 4 2 5 3 6]


Q3. Let x be array [[1, 2, 3], [4, 5, 6]]. Get the 5th element.

In [45]:
x = np.arange(1,7).reshape(2,3)
np.ravel(x)[4]

5

In [48]:
x = np.arange(1,7).reshape(2,3)
a = x.flat[4]
a

5

Q4. Let x be an arbitrary 3-D array of shape (3, 4, 5). Permute the dimensions of x such that the new shape will be (4,3,5).


In [58]:
x = np.zeros((3,4,5))
a = np.swapaxes(x, 1, 0)
a.shape

(4, 3, 5)

In [69]:
x = np.zeros((3,4,5))
a = x.transpose([1, 0, 2])
a.shape

(4, 3, 5)

Q5. Let x be an arbitrary 2-D array of shape (3, 4). Permute the dimensions of x such that the new shape will be (4,3).

In [73]:
x = np.zeros((3, 4))
a = x.transpose((1, 0))
a.shape

(4, 3)

In [74]:
x = np.zeros((3,4))
a = np.swapaxes(x, 1, 0)
a.shape

(4, 3)

Q5. Let x be an arbitrary 2-D array of shape (3, 4). Insert a nex axis such that the new shape will be (3, 1, 4).

In [92]:
x = np.zeros((3, 4))
a = np.expand_dims(x, 1)
a.shape

(3, 1, 4)

Q6. Let x be an arbitrary 3-D array of shape (3, 4, 1). Remove a single-dimensional entries such that the new shape will be (3, 4).

In [99]:
x = np.zeros((3, 4, 1))
a = np.squeeze(x)
a.shape

(3, 4)

Q7. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[1, 2, 3, 7, 8, 9], <br/>[4, 5, 6, 10, 11, 12]].


In [103]:
x = np.arange(1,7).reshape(2, 3)

y = np.arange(7,13).reshape(2, 3)

a = np.hstack((x, y))
print(a)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [106]:
x = np.arange(1,7).reshape(2, 3)

y = np.arange(7,13).reshape(2, 3)

a = np.concatenate((x, y), 1)
print(a)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Q8. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[ 1  2  3]<br/>
 [ 4  5  6]<br/>
 [ 7  8  9]<br/>
 [10 11 12]]


In [107]:
x = np.arange(1,7).reshape(2, 3)

y = np.arange(7,13).reshape(2, 3)

a = np.vstack((x, y))
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [108]:
x = np.arange(1,7).reshape(2, 3)

y = np.arange(7,13).reshape(2, 3)

a = np.concatenate((x, y), 0)
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Q8. Let x be an array [1 2 3] and y be [4 5 6]. Convert it to [[1, 4], [2, 5], [3, 6]].

In [120]:
x = np.array([1,2,3])
y = np.array([4,5,6])

a = np.vstack((x, y)).transpose()
print(a)

[[1 4]
 [2 5]
 [3 6]]


In [121]:
x = np.array([1,2,3])
y = np.array([4,5,6])

a = np.column_stack((x, y))
print(a)

[[1 4]
 [2 5]
 [3 6]]


Q9. Let x be an array [[1],[2],[3]] and y be [[4], [5], [6]]. Convert x to [[[1, 4]], [[2, 5]], [[3, 6]]].

In [123]:
x = np.array([[1],[2],[3]])
y = np.array([[4],[5],[6]])

a = np.dstack((x, y))
print(a)


[[[1 4]]

 [[2 5]]

 [[3 6]]]


Q10. Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [145]:
x = np.arange(1,11)
a = np.split(x, [3,7])
a

[array([1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10])]

Q11. Let x be an array<br/>
[[[  0.,   1.,   2.,   3.],<br/>
  [  4.,   5.,   6.,   7.]],<br/>
 
 [[  8.,   9.,  10.,  11.],<br/>
  [ 12.,  13.,  14.,  15.]]].<br/>
Split it into two such that the first array looks like<br/>
[[[  0.,   1.,   2.],<br/>
  [  4.,   5.,   6.]],<br/>
 
 [[  8.,   9.,  10.],<br/>
  [ 12.,  13.,  14.]]].<br/>
  
and the second one look like:<br/>
  
[[[  3.],<br/>
  [  7.]],<br/>
 
 [[  11.],<br/>
  [ 15.]]].<br/>  

In [195]:
x = np.arange(16).reshape(2, 2, 4)
np.split(x, [3], axis = 2)

[array([[[ 0,  1,  2],
         [ 4,  5,  6]],
 
        [[ 8,  9, 10],
         [12, 13, 14]]]),
 array([[[ 3],
         [ 7]],
 
        [[11],
         [15]]])]

In [167]:
x = np.arange(16).reshape(2, 2, 4)
np.dsplit(x, [3])

[array([[[ 0,  1,  2],
         [ 4,  5,  6]],
 
        [[ 8,  9, 10],
         [12, 13, 14]]]),
 array([[[ 3],
         [ 7]],
 
        [[11],
         [15]]])]

Q12. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the second axis.

In [199]:
x = np.arange(16).reshape((4, 4))
a = np.hsplit(x, 2)
print(a)

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [201]:
x = np.arange(16).reshape((4, 4))
a = np.split(x, 2, axis = 1)
print(a)

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


Q13. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the first axis.

In [202]:
x = np.arange(16).reshape((4, 4))
a = np.split(x, 2, axis = 0)
print(a)

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [203]:
x = np.arange(16).reshape((4, 4))
a = np.vsplit(x, 2)
print(a)

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


Q14. Let x be an array [0, 1, 2]. Convert it to <br/>
[[0, 1, 2, 0, 1, 2],<br/>
 [0, 1, 2, 0, 1, 2]].

In [214]:
x = np.array([0, 1, 2])
a = np.tile(x, [2,2])
print(a)

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


In [219]:
x = np.array([0, 1, 2])
a = np.resize(x, [2, 6])
print(a)

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


Q15. Let x be an array [0, 1, 2]. Convert it to <br/>
[0, 0, 1, 1, 2, 2].

In [221]:
x = np.array([0, 1, 2])
a = np.repeat(x, 2)
print(a)

[0 0 1 1 2 2]


Q16. Let x be an array [0, 0, 0, 1, 2, 3, 0, 2, 1, 0].<br/>
remove the leading the trailing zeros.

In [230]:
x = np.array([0, 0, 0, 1, 2, 3, 0, 2, 1, 0])
a = np.trim_zeros(x)
print(a)

[1 2 3 0 2 1]


Q17. Let x be an array [2, 2, 1, 5, 4, 5, 1, 2, 3]. Get two arrays of unique elements and their counts.


In [235]:
x = np.array([2, 2, 1, 5, 4, 5, 1, 2, 3])
a, counts = np.unique(x, return_counts = True)
print(a, counts)

[1 2 3 4 5] [2 3 1 1 2]


Q18. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the second axis.

In [244]:
x = np.array([[1, 2],[3, 4]])
a = np.flip(x, 1)
print(a)

[[2 1]
 [4 3]]


Q19. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the first axis.

In [251]:
x = np.array([[1, 2],[3, 4]])
a = np.flip(x, 0)
print(a)

[[3 4]
 [1 2]]


Q20. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Rotate x 90 degrees counter-clockwise.

In [256]:
x = np.array([[1, 2],[3, 4]])
a = np.rot90(x, 1)
print(a)

[[2 4]
 [1 3]]


Q21 Lex x be an array <br/>
[[ 1 2 3 4]<br/>
 [ 5 6 7 8].<br/>
Shift elements one step to right along the second axis.

In [257]:
x = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
a = np.roll(x, 1, axis=1)
print(a)

[[4 1 2 3]
 [8 5 6 7]]
