# Mathematical functions

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.3'

In [3]:
__author__ = "kyubyong. kbpark.linguist@gmail.com. https://github.com/kyubyong"

## Trigonometric functions

Q1. Calculate sine, cosine, and tangent of x, element-wise.

In [4]:
x = np.array([0., 1., 30, 90])
print("Sine: ", np.sin(x))
print("Coine: ", np.cos(x))
print("Tangent: ", np.tan(x))

Sine:  [ 0.          0.84147098 -0.98803162  0.89399666]
Coine:  [ 1.          0.54030231  0.15425145 -0.44807362]
Tangent:  [ 0.          1.55740772 -6.4053312  -1.99520041]


Q2. Calculate inverse sine, inverse cosine, and inverse tangent of x, element-wise.

In [5]:
x = np.array([-1., 0, 1.])
print("Inverse Sine: ", np.arcsin(x))
print("Inverse Cosine: ", np.arccos(x))
print("Inverse Tangent: ", np.arctan(x))

Inverse Sine:  [-1.57079633  0.          1.57079633]
Inverse Cosine:  [3.14159265 1.57079633 0.        ]
Inverse Tangent:  [-0.78539816  0.          0.78539816]


Q3. Convert angles from radians to degrees.

In [6]:
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])
print(np.degrees(x))

[-180.  -90.   90.  180.]


In [9]:
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])
print(np.rad2deg(x))

[-180.  -90.   90.  180.]


Q4. Convert angles from degrees to radians.

In [7]:
x = np.array([-180.,  -90.,   90.,  180.])
print(np.deg2rad(x))

[-3.14159265 -1.57079633  1.57079633  3.14159265]


In [10]:
x = np.array([-180.,  -90.,   90.,  180.])
print(np.radians(x))

[-3.14159265 -1.57079633  1.57079633  3.14159265]


## Hyperbolic functions

Q5. Calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent of x, element-wise.

In [8]:
x = np.array([-1., 0, 1.])
print(np.sinh(x))
print(np.cosh(x))
print(np.tanh(x))

[-1.17520119  0.          1.17520119]
[1.54308063 1.         1.54308063]
[-0.76159416  0.          0.76159416]


## Rounding

Q6. Predict the results of these, paying attention to the difference among the family functions.

In [11]:
x = np.array([2.1, 1.5, 2.5, 2.9, -2.1, -2.5, -2.9])

out1 = np.around(x)
out2 = np.floor(x)
out3 = np.ceil(x)
out4 = np.trunc(x)
out5 = [round(elem) for elem in x]

print(out1)
print(out2)
print(out3)
print(out4)
print(out5)

[ 2.  2.  2.  3. -2. -2. -3.]
[ 2.  1.  2.  2. -3. -3. -3.]
[ 3.  2.  3.  3. -2. -2. -2.]
[ 2.  1.  2.  2. -2. -2. -2.]
[2.0, 2.0, 2.0, 3.0, -2.0, -2.0, -3.0]


Q7. Implement out5 in the above question using numpy.

In [12]:
print(np.floor(np.abs(x) + 0.5) * np.sign(x))

[ 2.  2.  3.  3. -2. -3. -3.]


## Sums, products, differences

Q8. Predict the results of these.

In [14]:
x = np.array(
    [[1, 2, 3, 4],
     [5, 6, 7, 8]])

outs = [np.sum(x),
        np.sum(x, axis=0),
        np.sum(x, axis=1, keepdims=True),
        "",
        np.prod(x),
        np.prod(x, axis=0),
        np.prod(x, axis=1, keepdims=True),
        "",
        np.cumsum(x),
        np.cumsum(x, axis=0),
        np.cumsum(x, axis=1),
        "",
        np.cumprod(x),
        np.cumprod(x, axis=0),
        np.cumprod(x, axis=1),
        "",
        np.min(x),
        np.min(x, axis=0),
        np.min(x, axis=1, keepdims=True),
        "",
        np.max(x),
        np.max(x, axis=0),
        np.max(x, axis=1, keepdims=True),
        "",
        np.mean(x),
        np.mean(x, axis=0),
        np.mean(x, axis=1, keepdims=True)]
           
for out in outs:
    if out == "":
        pass
        print
    else:
        pass
        print("->", out)


-> 36
-> [ 6  8 10 12]
-> [[10]
 [26]]
-> 40320
-> [ 5 12 21 32]
-> [[  24]
 [1680]]
-> [ 1  3  6 10 15 21 28 36]
-> [[ 1  2  3  4]
 [ 6  8 10 12]]
-> [[ 1  3  6 10]
 [ 5 11 18 26]]
-> [    1     2     6    24   120   720  5040 40320]
-> [[ 1  2  3  4]
 [ 5 12 21 32]]
-> [[   1    2    6   24]
 [   5   30  210 1680]]
-> 1
-> [1 2 3 4]
-> [[1]
 [5]]
-> 8
-> [5 6 7 8]
-> [[4]
 [8]]
-> 4.5
-> [3. 4. 5. 6.]
-> [[2.5]
 [6.5]]


c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:34: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison


Q9. Calculate the difference between neighboring elements, element-wise.

In [15]:
x = np.array([1, 2, 4, 7, 0])
print(np.diff(x))

[ 1  2  3 -7]


Q10. Calculate the difference between neighboring elements, element-wise, and
prepend [0, 0] and append[100] to it.

In [17]:
x = np.array([1, 2, 4, 7, 0])
a = np.ediff1d(x, to_begin = [0, 0], to_end = [100])
print(a)

[  0   0   1   2   3  -7 100]


Q11. Return the cross product of x and y.

In [18]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
prod = np.cross(x, y)
print(prod)

[-3  6 -3]


## Exponents and logarithms

Q12. Compute $e^x$, element-wise.

In [20]:
x = np.array([1., 2., 3.], np.float32)
a = np.exp(x)
print(a)

[ 2.7182817  7.389056  20.085537 ]


Q13. Calculate exp(x) - 1 for all elements in x.

In [21]:
x = np.array([1., 2., 3.], np.float32)
a = np.exp(x) - 1
print(a)

[ 1.7182817  6.389056  19.085537 ]


In [ ]:
x = np.array([1., 2., 3.], np.float32)
a = np.expm1(x)
print(a)

Q14. Calculate $2^p$ for all p in x.

In [22]:
x = np.array([1., 2., 3.], np.float32)
a = np.exp2(x)
print(a)

[2. 4. 8.]


Q15. Compute natural, base 10, and base 2 logarithms of x element-wise.

In [23]:
x = np.array([1, np.e, np.e**2])
print("Natural log = ", np.log(x))
print("Common log = ", np.log10(x))
print("Base 2 log = ", np.log2(x))

Natural log =  [0. 1. 2.]
Common log =  [0.         0.43429448 0.86858896]
Base 2 log =  [0.         1.44269504 2.88539008]


Q16. Compute the natural logarithm of one plus each element in x in floating-point accuracy.

In [26]:
x = np.array([1e-99, 1e-100])
print(np.log1p(x))

[1.e-099 1.e-100]


## Floating point routines

Q17. Return element-wise True where signbit is set.

In [30]:
x = np.array([-3, -2, -1, 0, 1, 2, 3])
a = np.signbit(x)
print(a)

[ True  True  True False False False False]


In [31]:
x = np.array([-3, -2, -1, 0, 1, 2, 3])
a = x < 0
print(a)

[ True  True  True False False False False]


Q18. Change the sign of x to that of y, element-wise.

In [33]:
x = np.array([-1, 0, 1])
y = -1.1
print(np.copysign(x, y))

[-1. -0. -1.]


## Arithmetic operations

Q19. Add x and y element-wise.

In [34]:
x = np.array([1, 2, 3])
y = np.array([-1, -2, -3])
a = x + y
print(a)

[0 0 0]


In [36]:
x = np.array([1, 2, 3])
y = np.array([-1, -2, -3])
a = np.add(x, y)
print(a)

[0 0 0]


Q20. Subtract y from x element-wise.

In [37]:
x = np.array([3, 4, 5])
y = np.array(3)
a = x - y
print(a)

[0 1 2]


In [38]:
x = np.array([3, 4, 5])
y = np.array(3)
a = np.subtract(x, y)
print(a)

[0 1 2]


Q21. Multiply x by y element-wise.

In [39]:
x = np.array([3, 4, 5])
y = np.array([1, 0, -1])
a = np.multiply(x, y)
print(a)

[ 3  0 -5]


In [41]:
x = np.array([3, 4, 5])
y = np.array([1, 0, -1])
a = x * y
print(a)

[ 3  0 -5]


Q22. Divide x by y element-wise in two different ways.

In [42]:
x = np.array([3., 4., 5.])
y = np.array([1., 2., 3.])
a = x / y
print(a)

[3.         2.         1.66666667]


In [43]:
x = np.array([3., 4., 5.])
y = np.array([1., 2., 3.])
a = np.divide(x, y)
print(a)

[3.         2.         1.66666667]


Q23. Compute numerical negative value of x, element-wise.

In [46]:
x = np.array([1, -1])
print(np.negative(x))

[-1  1]


Q24. Compute the reciprocal of x, element-wise.

In [47]:
x = np.array([1., 2., .2])
print(np.reciprocal(x))

[1.  0.5 5. ]


In [48]:
x = np.array([1., 2., .2])
print(1/x)

[1.  0.5 5. ]


Q25. Compute $x^y$, element-wise.

In [49]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [1, 2]])
print(x ** y)

[[ 1  4]
 [ 3 16]]


In [50]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [1, 2]])
a = np.power(x, y)
print(a)

[[ 1  4]
 [ 3 16]]


Q26. Compute the remainder of x / y element-wise in two different ways.

In [51]:
x = np.array([-3, -2, -1, 1, 2, 3])
y = 2
print(x % y)

[1 0 1 1 0 1]


In [52]:
x = np.array([-3, -2, -1, 1, 2, 3])
y = 2
a = np.mod(x, y)
print(a)

[1 0 1 1 0 1]


## Miscellaneous

Q27. If an element of x is smaller than 3, replace it with 3.
And if an element of x is bigger than 7, replace it with 7.

In [56]:
x = np.arange(10)
a = np.clip(x, 3, 7)
print(a)

[3 3 3 3 4 5 6 7 7 7]


In [58]:
x = np.arange(10)
x[x < 3] = 3
x[x > 7] = 7
print(x)

[3 3 3 3 4 5 6 7 7 7]


Q28. Compute the square of x, element-wise.

In [80]:
x = np.array([1, 2, -1])
a = np.square(x)
b = x ** 2
assert np.array_equiv(a, b)
print(b)

[1 4 1]


Q29. Compute square root of x element-wise.


In [79]:
x = np.array([1., 4., 9.])
a = np.sqrt(x)
b = x ** 0.5
assert np.array_equiv(a, b)
print(a)

[1. 2. 3.]


Q30. Compute the absolute value of x.

In [81]:
x = np.array([[1, -1], [3, -3]])
a = np.abs(x)
a1 = np.absolute(x)
assert np.array_equiv(a, a1)
print(a)

[[1 1]
 [3 3]]


Q31. Compute an element-wise indication of the sign of x, element-wise.

In [82]:
x = np.array([1, 3, 0, -1, -3])
a = np.sign(x)
print(a)

[ 1  1  0 -1 -1]
